<a href="https://colab.research.google.com/github/AasthaGiri/Week-5/blob/main/RNN_PGS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
sentences = [
    "The weather is beautiful today",
    "I hate waiting in long lines",
    "She achieved her lifelong dream",
    "This restaurant service was terrible",
    "The car broke down in the middle of the road",
    "I enjoy painting landscapes",
    "It was a thrilling experience",
    "He solved a complex puzzle effortlessly",
    "We should care for the environment",
    "The new smartphone model is overpriced"
]


In [ ]:
label = [1, 0, 1, 0, 0, 0, 1, 1, 1, 1]

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
tokens = Tokenizer(oov_token = 'oov')
tokens.fit_on_texts(sentences)

In [ ]:
vocab = tokens.word_index

In [ ]:
vocab

{'oov': 1,
 'the': 2,
 'is': 3,
 'i': 4,
 'in': 5,
 'was': 6,
 'a': 7,
 'weather': 8,
 'beautiful': 9,
 'today': 10,
 'hate': 11,
 'waiting': 12,
 'long': 13,
 'lines': 14,
 'she': 15,
 'achieved': 16,
 'her': 17,
 'lifelong': 18,
 'dream': 19,
 'this': 20,
 'restaurant': 21,
 'service': 22,
 'terrible': 23,
 'car': 24,
 'broke': 25,
 'down': 26,
 'middle': 27,
 'of': 28,
 'road': 29,
 'enjoy': 30,
 'painting': 31,
 'landscapes': 32,
 'it': 33,
 'thrilling': 34,
 'experience': 35,
 'he': 36,
 'solved': 37,
 'complex': 38,
 'puzzle': 39,
 'effortlessly': 40,
 'we': 41,
 'should': 42,
 'care': 43,
 'for': 44,
 'environment': 45,
 'new': 46,
 'smartphone': 47,
 'model': 48,
 'overpriced': 49}

In [ ]:
sequence = tokens.texts_to_sequences(sentences)

In [ ]:
sequence

[[2, 8, 3, 9, 10],
 [4, 11, 12, 5, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 6, 23],
 [2, 24, 25, 26, 5, 2, 27, 28, 2, 29],
 [4, 30, 31, 32],
 [33, 6, 7, 34, 35],
 [36, 37, 7, 38, 39, 40],
 [41, 42, 43, 44, 2, 45],
 [2, 46, 47, 48, 3, 49]]

In [ ]:
sequences = pad_sequences(sequence, maxlen=6, padding = 'post', truncating='post')

In [ ]:
sequences

array([[ 2,  8,  3,  9, 10,  0],
       [ 4, 11, 12,  5, 13, 14],
       [15, 16, 17, 18, 19,  0],
       [20, 21, 22,  6, 23,  0],
       [ 2, 24, 25, 26,  5,  2],
       [ 4, 30, 31, 32,  0,  0],
       [33,  6,  7, 34, 35,  0],
       [36, 37,  7, 38, 39, 40],
       [41, 42, 43, 44,  2, 45],
       [ 2, 46, 47, 48,  3, 49]], dtype=int32)

In [ ]:
sequences.shape

(10, 6)

In [ ]:
 sequences.shape[0]

10

In [ ]:
label = np.array(label).reshape(-1)

In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(SimpleRNN(1, input_shape=(sequences.shape[1],1), activation = 'relu' ))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(sequences, label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.4000 - loss: 25.4901


In [ ]:
test = ['The stars shimmered brightly in the clear night sky.']

In [ ]:
# tokens.fit_on_texts(test)

In [ ]:
test = tokens.texts_to_sequences(test)

In [ ]:
test = pad_sequences(test, padding = 'post', truncating = 'post', maxlen = 6)

In [ ]:
test

array([[2, 1, 1, 1, 5, 2]], dtype=int32)

In [ ]:
test.shape

(1, 6)

In [ ]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[0.02637881]], dtype=float32)

In [ ]:
tokens.word_index

{'oov': 1,
 'the': 2,
 'is': 3,
 'i': 4,
 'in': 5,
 'was': 6,
 'a': 7,
 'weather': 8,
 'beautiful': 9,
 'today': 10,
 'hate': 11,
 'waiting': 12,
 'long': 13,
 'lines': 14,
 'she': 15,
 'achieved': 16,
 'her': 17,
 'lifelong': 18,
 'dream': 19,
 'this': 20,
 'restaurant': 21,
 'service': 22,
 'terrible': 23,
 'car': 24,
 'broke': 25,
 'down': 26,
 'middle': 27,
 'of': 28,
 'road': 29,
 'enjoy': 30,
 'painting': 31,
 'landscapes': 32,
 'it': 33,
 'thrilling': 34,
 'experience': 35,
 'he': 36,
 'solved': 37,
 'complex': 38,
 'puzzle': 39,
 'effortlessly': 40,
 'we': 41,
 'should': 42,
 'care': 43,
 'for': 44,
 'environment': 45,
 'new': 46,
 'smartphone': 47,
 'model': 48,
 'overpriced': 49}